sudo: required
services:
  - docker

before_install:
  - docker build -t aneez004/docker-react -f Dockerfile.dev .

script:
  - docker run aneez004/docker-react npm run test -- --coverage

install: travis_wait mvn install
